# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
  	web.vm.box = "centos/7"
  	web.vm.network "private_network", ip: "192.168.0.10"
  	web.vm.provision "shell", inline: <<-SHELL
  		echo "webserver" > /etc/hostname
  		hostname -b webserver
  		echo "192.168.0.20 clockserver" >> /etc/hosts
  	SHELL
  end
  config.vm.define "clock" do |clock|
  	clock.vm.box = "centos/7"
  	clock.vm.network "private_network", ip: "192.168.0.20"
  	clock.vm.provision "shell", inline: <<-SHELL
  		echo "clockserver" > /etc/hostname
  		hostname -b clockserver
  		echo "192.168.0.10 webserver" >> /etc/hosts
	SHELL
  end
end
